services:
  dixvisiondashboard2026:
    image: dixvisiondashboard2026
    build:
      context: dashboard2026
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
