"""Canonical typed contracts shared by all engines.

Importing this package is **always** allowed for every engine — it is the
common allow-listed dependency in the authority-lint rule set
(``tools/authority_lint.py`` rules T1, C2, C3, W1, L1, L2, L3, B1).
"""

from core.contracts.engine import (
    Engine,
    EngineTier,
    HealthState,
    HealthStatus,
    OfflineEngine,
    Plugin,
    PluginLifecycle,
    RuntimeEngine,
)
from core.contracts.events import (
    Event,
    EventKind,
    ExecutionEvent,
    ExecutionStatus,
    HazardEvent,
    HazardSeverity,
    Side,
    SignalEvent,
    SystemEvent,
    SystemEventKind,
)
from core.contracts.cognitive_observability import (
    INDIRA_COGNITION_STREAM,
    DYON_SYSTEM_STREAM,
    CognitiveIntelligence,
    CognitiveEventKind,
    MemoryKind,
    GovernanceStatus,
    DriftSeverity,
    RepairStage,
    RepairOutcome,
    PatchKind,
    DependencyAnomalyKind,
    ThoughtStreamEvent,
    BeliefEvolutionEvent,
    MemoryFormationEvent,
    MutationTraceEvent,
    ConfidenceShiftEvent,
    ArchetypeEvolutionEvent,
    CausalChainEvent,
    ResearchDiscoveryEvent,
    PatchProposalEvent,
    TopologyDriftEvent,
    ArchitecturalDriftEvent,
    RepairPipelineEvent,
    DependencyAnomalyEvent,
    RuntimeAnomalyEvent,
    CognitiveObservabilityProjection,
    AnyIndiraEvent,
    AnyDyonEvent,
    AnyCognitiveEvent,
)

__all__ = [
    "Engine",
    "EngineTier",
    "Event",
    "EventKind",
    "ExecutionEvent",
    "ExecutionStatus",
    "HazardEvent",
    "HazardSeverity",
    "HealthState",
    "HealthStatus",
    "OfflineEngine",
    "Plugin",
    "PluginLifecycle",
    "RuntimeEngine",
    "Side",
    "SignalEvent",
    "SystemEvent",
    "SystemEventKind",
    # Cognitive observability
    "INDIRA_COGNITION_STREAM",
    "DYON_SYSTEM_STREAM",
    "CognitiveIntelligence",
    "CognitiveEventKind",
    "MemoryKind",
    "GovernanceStatus",
    "DriftSeverity",
    "RepairStage",
    "RepairOutcome",
    "PatchKind",
    "DependencyAnomalyKind",
    "ThoughtStreamEvent",
    "BeliefEvolutionEvent",
    "MemoryFormationEvent",
    "MutationTraceEvent",
    "ConfidenceShiftEvent",
    "ArchetypeEvolutionEvent",
    "CausalChainEvent",
    "ResearchDiscoveryEvent",
    "PatchProposalEvent",
    "TopologyDriftEvent",
    "ArchitecturalDriftEvent",
    "RepairPipelineEvent",
    "DependencyAnomalyEvent",
    "RuntimeAnomalyEvent",
    "CognitiveObservabilityProjection",
    "AnyIndiraEvent",
    "AnyDyonEvent",
    "AnyCognitiveEvent",
]
