# ADAPTED FROM: KangOxford/jax-lob
# (gymnax_exchange/jaxob/JaxOrderBookArrays.py — add_order, cancel_order, match_order;
#  gymnax_exchange/jaxob/jorderbook.py — OrderBook class, LobState NamedTuple,
#  process_orders_array, get_best_bid/ask, get_L2_state;
#  gymnax_exchange/jaxob/JaxOrderBookArrays.py — scan_through_entire_array,
#  cond_type_side, get_volume_at_price.)
"""C-46 — Vectorized LOB simulation for batch adversarial evaluation.

This module adapts the JAX-LOB project
(https://github.com/KangOxford/jax-lob, MIT License) as a batch LOB
simulator for adversarial scenario evaluation. JAX-LOB's design uses
JAX jit+vmap to process thousands of order books in parallel on GPU;
this adaptation reproduces the *architecture* (array-backed order books,
functional state transitions, batch processing) in pure Python so the
module is importable without JAX installed.

What survives from upstream (KangOxford/jax-lob):

* **LobState as a NamedTuple** — ``jorderbook.py`` line 15: the order
  book state is a named triple ``(asks, bids, trades)`` where each
  element is a fixed-size 2D array. We reproduce this as a frozen
  dataclass with list-of-lists backing.
* **Functional order processing** — ``JaxOrderBookArrays.py``
  ``add_order``, ``cancel_order``, ``match_order`` are standalone
  functions that take the state and a message array and return new state.
  We mirror this with ``process_message()`` operating on ``BookState``.
* **Batch scanning** — ``scan_through_entire_array`` processes an Nx8
  message array sequentially through the book. We reproduce this as
  ``process_message_batch()`` (sequential) and ``run_parallel_books()``
  (simulated vmap over multiple independent books).
* **Order format** — each order is [type, side, quantity, price,
  order_id, trader_id, time_s, time_ns] matching JAX-LOB's int32
  8-column convention.

What we replaced:

* JAX ``jnp.array`` and ``@jax.jit`` → plain Python lists and loops.
  The Protocol seam ``ArrayBackend`` allows optional JAX acceleration
  via lazy import (tested by injecting a fake).
* ``jax.lax.scan`` → explicit Python loop in ``process_message_batch``.
* ``jax.vmap`` → ``run_parallel_books()`` using sequential iteration
  (or ThreadPoolExecutor in production with injected parallelism).

DIX integration rules:

* OFFLINE simulation tier only. No IO, no clock reads.
* Deterministic: same message sequence → same final state.
* INV-15: BLAKE2b digest computed over book state for replay.
* No JAX import at module level — hidden behind Protocol seam.
"""

from __future__ import annotations

import dataclasses
import hashlib
from collections.abc import Sequence
from typing import Final, NamedTuple, Protocol, runtime_checkable

JAX_LOB_SIM_VERSION: Final[str] = "c-46.v1"
NEW_PIP_DEPENDENCIES: tuple[str, ...] = ()

# ---------------------------------------------------------------------------
# Constants matching JAX-LOB conventions
# ---------------------------------------------------------------------------

INIT_ID: Final[int] = -9000
"""Sentinel for initial orders without explicit ID (JAX-LOB INITID)."""

EMPTY: Final[int] = -1
"""Empty slot sentinel (JAX-LOB uses -1 for empty array positions)."""

# Message type codes (matching JAX-LOB inttype mapping in jorderbook.py:60-73)
MSG_LIMIT: Final[int] = 1
MSG_CANCEL: Final[int] = 2
MSG_MARKET: Final[int] = 3

# Side codes
SIDE_ASK: Final[int] = 0
SIDE_BID: Final[int] = 1


# ---------------------------------------------------------------------------
# Protocol seam for optional JAX acceleration
# ---------------------------------------------------------------------------


@runtime_checkable
class ArrayBackend(Protocol):
    """Protocol for array operations — default is pure Python lists."""

    def zeros(self, shape: tuple[int, int]) -> list[list[int]]: ...

    def process(self, state: BookState, msg: OrderMessage) -> BookState: ...


# ---------------------------------------------------------------------------
# Value objects (mirrors JAX-LOB's LobState NamedTuple + msg array)
# ---------------------------------------------------------------------------


class OrderMessage(NamedTuple):
    """Single order message matching JAX-LOB's 8-column format.

    Fields:
        msg_type: 1=limit, 2=cancel, 3=market
        side: 0=ask, 1=bid
        quantity: order quantity
        price: order price (integer ticks)
        order_id: unique order identifier
        trader_id: trader identifier
        time_s: timestamp seconds
        time_ns: timestamp nanoseconds
    """

    msg_type: int
    side: int
    quantity: int
    price: int
    order_id: int
    trader_id: int
    time_s: int
    time_ns: int


@dataclasses.dataclass(frozen=True, slots=True)
class TradeRecord:
    """Single trade generated by matching.

    Matches JAX-LOB's trade array format:
    [price, quantity, resting_order_id, aggressor_order_id, time_s, time_ns]
    """

    price: int
    quantity: int
    resting_order_id: int
    aggressor_order_id: int
    time_s: int
    time_ns: int


@dataclasses.dataclass(slots=True)
class BookState:
    """Mutable order book state mirroring JAX-LOB's LobState.

    Each side is a list of orders, where each order is:
    [price, quantity, order_id, trader_id, time_s, time_ns]
    matching JAX-LOB's 6-column orderside array.
    """

    asks: list[list[int]]
    bids: list[list[int]]
    trades: list[TradeRecord]
    n_orders: int
    n_trades: int

    def copy(self) -> BookState:
        return BookState(
            asks=[row[:] for row in self.asks],
            bids=[row[:] for row in self.bids],
            trades=list(self.trades),
            n_orders=self.n_orders,
            n_trades=self.n_trades,
        )


@dataclasses.dataclass(frozen=True, slots=True)
class L2Snapshot:
    """Level-2 book snapshot (top N price levels aggregated).

    Mirrors JAX-LOB's ``get_L2_state`` output.
    """

    best_bid: int
    best_ask: int
    bid_levels: tuple[tuple[int, int], ...]  # (price, total_qty)
    ask_levels: tuple[tuple[int, int], ...]  # (price, total_qty)
    spread: int
    mid_price_x2: int  # 2 * mid_price to avoid float (integer ticks)


@dataclasses.dataclass(frozen=True, slots=True)
class BatchResult:
    """Result of running multiple books in parallel (simulated vmap).

    Attributes:
        final_states: Final book states for each parallel book.
        digests: BLAKE2b digests per book for INV-15.
        l2_snapshots: Final L2 snapshots per book.
    """

    final_states: tuple[BookState, ...]
    digests: tuple[str, ...]
    l2_snapshots: tuple[L2Snapshot, ...]


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class JaxLobSimError(ValueError):
    """Errors specific to the JAX-LOB simulation module."""


# ---------------------------------------------------------------------------
# Core functions (mirrors JaxOrderBookArrays.py functional style)
# ---------------------------------------------------------------------------


def make_book_state(n_orders: int = 100, n_trades: int = 100) -> BookState:
    """Create empty book state (mirrors OrderBook.init in jorderbook.py:31-35)."""
    return BookState(
        asks=[],
        bids=[],
        trades=[],
        n_orders=n_orders,
        n_trades=n_trades,
    )


def _add_order(side_orders: list[list[int]], msg: OrderMessage) -> None:
    """Add a limit order to the given side (mirrors JaxOrderBookArrays.add_order).

    Orders are inserted in price-time priority:
    - Asks: ascending price, then ascending time
    - Bids: descending price, then ascending time
    """
    order = [msg.price, msg.quantity, msg.order_id, msg.trader_id, msg.time_s, msg.time_ns]
    side_orders.append(order)


def _cancel_order(side_orders: list[list[int]], msg: OrderMessage) -> None:
    """Cancel/reduce quantity (mirrors JaxOrderBookArrays.cancel_order).

    Finds order by order_id first, falls back to price match with INIT_ID
    (same as JAX-LOB's cancel_order fallback logic).
    """
    # First try exact order_id match
    for i, order in enumerate(side_orders):
        if order[2] == msg.order_id:
            order[1] -= msg.quantity
            if order[1] <= 0:
                side_orders.pop(i)
            return

    # Fallback: match by price with init IDs (JAX-LOB init_id_match)
    for i, order in enumerate(side_orders):
        if order[0] == msg.price and order[2] <= INIT_ID:
            order[1] -= msg.quantity
            if order[1] <= 0:
                side_orders.pop(i)
            return


def _get_top_bid_idx(bids: list[list[int]]) -> int | None:
    """Get index of best bid (highest price, earliest time).

    Mirrors JaxOrderBookArrays.__get_top_bid_order_idx.
    """
    if not bids:
        return None
    best_idx = 0
    best_price = bids[0][0]
    best_time_s = bids[0][4]
    best_time_ns = bids[0][5]
    for i in range(1, len(bids)):
        p, _, _, _, ts, tns = bids[i]
        if p > best_price or (
            p == best_price and (ts < best_time_s or (ts == best_time_s and tns < best_time_ns))
        ):
            best_idx = i
            best_price = p
            best_time_s = ts
            best_time_ns = tns
    return best_idx


def _get_top_ask_idx(asks: list[list[int]]) -> int | None:
    """Get index of best ask (lowest price, earliest time).

    Mirrors JaxOrderBookArrays.__get_top_ask_order_idx.
    """
    if not asks:
        return None
    best_idx = 0
    best_price = asks[0][0]
    best_time_s = asks[0][4]
    best_time_ns = asks[0][5]
    for i in range(1, len(asks)):
        p, _, _, _, ts, tns = asks[i]
        if p < best_price or (
            p == best_price and (ts < best_time_s or (ts == best_time_s and tns < best_time_ns))
        ):
            best_idx = i
            best_price = p
            best_time_s = ts
            best_time_ns = tns
    return best_idx


def _match_order(
    side_orders: list[list[int]],
    top_idx: int,
    msg: OrderMessage,
    trades: list[TradeRecord],
) -> int:
    """Match against top order, return remaining quantity.

    Mirrors JaxOrderBookArrays.match_order: reduces resting order qty,
    generates trade record, removes if fully filled.
    """
    resting = side_orders[top_idx]
    fill_qty = min(msg.quantity, resting[1])

    trade = TradeRecord(
        price=resting[0],
        quantity=fill_qty,
        resting_order_id=resting[2],
        aggressor_order_id=msg.order_id,
        time_s=msg.time_s,
        time_ns=msg.time_ns,
    )
    trades.append(trade)

    resting[1] -= fill_qty
    if resting[1] <= 0:
        side_orders.pop(top_idx)

    return msg.quantity - fill_qty


def process_message(state: BookState, msg: OrderMessage) -> BookState:
    """Process a single message against the book state.

    Mirrors JAX-LOB's cond_type_side dispatch logic in
    JaxOrderBookArrays.py which routes based on msg_type and side.
    """
    if msg.msg_type == MSG_LIMIT:
        if msg.side == SIDE_BID:
            # Check if crosses best ask (marketable)
            remaining = msg.quantity
            while remaining > 0:
                ask_idx = _get_top_ask_idx(state.asks)
                if ask_idx is None:
                    break
                if state.asks[ask_idx][0] > msg.price:
                    break
                fill_msg = msg._replace(quantity=remaining)
                remaining = _match_order(state.asks, ask_idx, fill_msg, state.trades)
            if remaining > 0:
                rest_msg = msg._replace(quantity=remaining)
                _add_order(state.bids, rest_msg)
        else:
            # ASK limit
            remaining = msg.quantity
            while remaining > 0:
                bid_idx = _get_top_bid_idx(state.bids)
                if bid_idx is None:
                    break
                if state.bids[bid_idx][0] < msg.price:
                    break
                fill_msg = msg._replace(quantity=remaining)
                remaining = _match_order(state.bids, bid_idx, fill_msg, state.trades)
            if remaining > 0:
                rest_msg = msg._replace(quantity=remaining)
                _add_order(state.asks, rest_msg)

    elif msg.msg_type == MSG_CANCEL:
        if msg.side == SIDE_BID:
            _cancel_order(state.bids, msg)
        else:
            _cancel_order(state.asks, msg)

    elif msg.msg_type == MSG_MARKET:
        # Market order: match against opposite side until filled
        remaining = msg.quantity
        if msg.side == SIDE_BID:
            # Market buy matches against asks
            while remaining > 0:
                ask_idx = _get_top_ask_idx(state.asks)
                if ask_idx is None:
                    break
                fill_msg = msg._replace(quantity=remaining)
                remaining = _match_order(state.asks, ask_idx, fill_msg, state.trades)
        else:
            # Market sell matches against bids
            while remaining > 0:
                bid_idx = _get_top_bid_idx(state.bids)
                if bid_idx is None:
                    break
                fill_msg = msg._replace(quantity=remaining)
                remaining = _match_order(state.bids, bid_idx, fill_msg, state.trades)

    return state


def process_message_batch(
    state: BookState,
    messages: Sequence[OrderMessage],
) -> BookState:
    """Process array of messages sequentially.

    Mirrors JAX-LOB's scan_through_entire_array which uses
    jax.lax.scan to fold messages through the book state.
    """
    for msg in messages:
        process_message(state, msg)
    return state


def get_best_bid(state: BookState) -> int | None:
    """Get best bid price (mirrors jorderbook.py get_best_bid)."""
    idx = _get_top_bid_idx(state.bids)
    if idx is None:
        return None
    return state.bids[idx][0]


def get_best_ask(state: BookState) -> int | None:
    """Get best ask price (mirrors jorderbook.py get_best_ask)."""
    idx = _get_top_ask_idx(state.asks)
    if idx is None:
        return None
    return state.asks[idx][0]


def get_l2_snapshot(state: BookState, n_levels: int = 5) -> L2Snapshot:
    """Get Level-2 snapshot (mirrors jorderbook.py get_L2_state).

    Aggregates quantity at each price level, returns top N levels
    per side.
    """
    # Aggregate bids by price (descending)
    bid_agg: dict[int, int] = {}
    for order in state.bids:
        bid_agg[order[0]] = bid_agg.get(order[0], 0) + order[1]
    bid_levels = sorted(bid_agg.items(), key=lambda x: -x[0])[:n_levels]

    # Aggregate asks by price (ascending)
    ask_agg: dict[int, int] = {}
    for order in state.asks:
        ask_agg[order[0]] = ask_agg.get(order[0], 0) + order[1]
    ask_levels = sorted(ask_agg.items(), key=lambda x: x[0])[:n_levels]

    best_bid = bid_levels[0][0] if bid_levels else 0
    best_ask = ask_levels[0][0] if ask_levels else 0
    spread = (best_ask - best_bid) if (best_bid and best_ask) else 0
    mid_x2 = (best_bid + best_ask) if (best_bid and best_ask) else 0

    return L2Snapshot(
        best_bid=best_bid,
        best_ask=best_ask,
        bid_levels=tuple(bid_levels),
        ask_levels=tuple(ask_levels),
        spread=spread,
        mid_price_x2=mid_x2,
    )


def compute_state_digest(state: BookState) -> str:
    """BLAKE2b digest of book state for INV-15 replay verification."""
    h = hashlib.blake2b(digest_size=16)
    h.update(len(state.bids).to_bytes(4, "little"))
    h.update(len(state.asks).to_bytes(4, "little"))
    h.update(len(state.trades).to_bytes(4, "little"))
    for order in sorted(state.bids, key=lambda o: (o[0], o[4], o[5], o[2])):
        for v in order:
            h.update(v.to_bytes(8, "little", signed=True))
    for order in sorted(state.asks, key=lambda o: (o[0], o[4], o[5], o[2])):
        for v in order:
            h.update(v.to_bytes(8, "little", signed=True))
    for t in state.trades:
        h.update(t.price.to_bytes(8, "little", signed=True))
        h.update(t.quantity.to_bytes(8, "little", signed=True))
        h.update(t.resting_order_id.to_bytes(8, "little", signed=True))
        h.update(t.aggressor_order_id.to_bytes(8, "little", signed=True))
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Batch / parallel execution (simulated vmap)
# ---------------------------------------------------------------------------


def run_parallel_books(
    n_books: int,
    messages_per_book: Sequence[Sequence[OrderMessage]],
    *,
    n_orders: int = 100,
    n_trades: int = 100,
) -> BatchResult:
    """Run multiple independent books in parallel (simulated vmap).

    Mirrors JAX-LOB's vmap pattern where the same message processing
    logic is vectorized across thousands of independent books on GPU.
    In pure Python we process sequentially but maintain the same
    interface for drop-in JAX acceleration.

    Args:
        n_books: Number of parallel books.
        messages_per_book: Message sequences for each book.
        n_orders: Max orders per side per book.
        n_trades: Max trades per book.

    Returns:
        BatchResult with final states, digests, and L2 snapshots.
    """
    if len(messages_per_book) != n_books:
        raise JaxLobSimError(
            f"messages_per_book length {len(messages_per_book)} != n_books {n_books}"
        )

    final_states: list[BookState] = []
    digests: list[str] = []
    l2_snapshots: list[L2Snapshot] = []

    for msgs in messages_per_book:
        state = make_book_state(n_orders=n_orders, n_trades=n_trades)
        process_message_batch(state, msgs)
        final_states.append(state)
        digests.append(compute_state_digest(state))
        l2_snapshots.append(get_l2_snapshot(state))

    return BatchResult(
        final_states=tuple(final_states),
        digests=tuple(digests),
        l2_snapshots=tuple(l2_snapshots),
    )


# ---------------------------------------------------------------------------
# Module exports
# ---------------------------------------------------------------------------


__all__ = [
    "EMPTY",
    "INIT_ID",
    "JAX_LOB_SIM_VERSION",
    "NEW_PIP_DEPENDENCIES",
    "MSG_CANCEL",
    "MSG_LIMIT",
    "MSG_MARKET",
    "ArrayBackend",
    "BatchResult",
    "BookState",
    "JaxLobSimError",
    "L2Snapshot",
    "OrderMessage",
    "SIDE_ASK",
    "SIDE_BID",
    "TradeRecord",
    "compute_state_digest",
    "get_best_ask",
    "get_best_bid",
    "get_l2_snapshot",
    "make_book_state",
    "process_message",
    "process_message_batch",
    "run_parallel_books",
]
